"""empty message

Revision ID: 7f06687ab15f
Revises: ffdc0a98111c
Create Date: 2023-09-06 11:58:46.659098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f06687ab15f'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstName', sa.String(length=40), nullable=True))
    op.add_column('users', sa.Column('lastName', sa.String(length=40), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=40), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'state')
    op.drop_column('users', 'city')
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'firstName')
    # ### end Alembic commands ###