"""empty message

Revision ID: dbcacf627fec
Revises: 7f06687ab15f
Create Date: 2023-09-06 12:05:23.113892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbcacf627fec'
down_revision = '7f06687ab15f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boardId', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=40), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['boardId'], ['boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('pinId', sa.String(length=40), nullable=False),
    sa.Column('commentText', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['pinId'], ['pins.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pins-to-boards',
    sa.Column('pin_id', sa.Integer(), nullable=True),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['pin_id'], ['pins.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pins-to-boards')
    op.drop_table('comments')
    op.drop_table('pins')
    op.drop_table('boards')
    # ### end Alembic commands ###